### ISSUE TITLE
Faced issue while running your notebook on rasa core 0.12.4

### ISSUE THREAD

**Issue by rremani** [parulnith/Building-a-Conversational-Chatbot-for-Slack-using-Rasa-and-Python#1]
It's running perfectly fine on the version you have specified. 

Problem is with the custom action class. As per the latest document we need to use the string returned by the name function of the custom class in the domain.yml file under actions. But it wasn't working. Tried representing the way it was used for an earlier version, wasn't working too.

Any ideas to use it with the new version would be helpful.

**Comment by GDBSD** [comment]
Based on my experience you should not expect _any_ Rasa example to work with the versions other than the ones used for the example. Seems like every version is loaded with breaking changes.

**Comment by rremani** [comment]
@GDBSD True
